MOV 12H, #3
MOV 13H, #1
MOV 14H, #10
MOV 15H, #2
MOV 16H, #8

MOV R0, #12H
MOV R7, #04H
MOV A, @R0							; INITIALIZING A WITH FIRST NUMBER
BACK: INC R0
MOV 06H, @R0
CJNE A, 06H, L1                     ;A-R6 -> IF NUM IN A IS NOT EQUAL TO R6
SJMP L2
L1: JNC L2                          ;CHECK FOR CARRY FLAG, IF CY=0(MEANS A IS GREATER) JUMP TO L2, OTHERWISE IF CY=1(R6 IS GREATER)
MOV A, R6							;STORING R6 VAL IN A COZ R6 GREATER
L2: DJNZ R7, BACK
MOV R1, A                           ;STORING RESULT IN R1
END